name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        include:
          - os: windows
            extension: ".exe"
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Build
        run: |
          go build -v -o hue-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }} -ldflags="-X 'main.version=${{ github.event.release.tag_name }}'" .
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload Release Assets
        uses: SierraSoftworks/gh-releases@v1.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          files: |
            hue-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}

  tap:
    name: Update Homebrew Tap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Update Homebrew Tap
        uses: SierraSoftworks/actions-tap@v1
        with:
          app-id: ${{ secrets.TAP_APP_ID }}
          private-key: ${{ secrets.TAP_APP_PRIVATE_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          desc: Control your Philips Hue lights from your command line
